version: "3"
services:
  app:
    build: .
    command: bash -c "pipenv run python manage.py runserver"
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    env_file: 
      - prod.env
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file: 
      - prod.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE
    volumes:
      - ocr-db:/var/lib/mysql
volumes:
  ocr-db:
    driver: local